# Generated by Django 3.1 on 2020-08-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
    ]
