# Generated by Django 3.1 on 2021-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
