# Generated by Django 3.1 on 2020-08-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200820_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_letter',
        ),
    ]
