# Generated by Django 4.0.2 on 2022-03-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20220202_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section_number',
            field=models.IntegerField(default=1),
        ),
    ]
