# Generated by Django 4.0.2 on 2022-03-09 16:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_question_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
