# Generated by Django 4.0.2 on 2022-03-09 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_user_used_question_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_question_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
