# Generated by Django 4.0.2 on 2022-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_user_used_question_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_number',
            field=models.IntegerField(default=0),
        ),
    ]
