# Generated by Django 4.0.2 on 2022-03-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_user_image_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_number',
        ),
        migrations.AddField(
            model_name='question',
            name='image_number',
            field=models.IntegerField(default=0),
        ),
    ]
