# Generated by Django 4.0.2 on 2022-03-16 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_user_image_number_question_image_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None), default=list, size=None),
        ),
    ]
