# Generated by Django 4.0.3 on 2022-04-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_user_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='QuestionChoices',
        ),
        migrations.RemoveField(
            model_name='incorrectchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='incorrectchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='incorrectchoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='IncorrectChoice',
        ),
    ]
