# Generated by Django 4.0.3 on 2022-04-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_rename_answer_questionchoices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='percentage',
            new_name='crowd_percentage',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='correct',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section_number',
        ),
    ]
